version: "2"

services:
  db:
    image: mysql
    restart: always
    volumes:
      - ./mysql/runtime:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
  app:
    image: piwik
    restart: always
    links:
      - db
    volumes:
      - ./config:/var/www/html/config
      - ./ssmtp.conf:/etc/ssmtp/ssmtp.conf
      - ./revaliases:/etc/ssmtp/revaliases
  web:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    ports:
      - 80
      - 443
    volumes_from:
      - app
    environment:
      VIRTUAL_HOST: piwik.enliven.se

  cron:
    image: piwik
    links:
      - db
    volumes_from:
      - app
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        su -s "/bin/bash" -c "/usr/local/bin/php /var/www/html/console core:archive" www-data
        sleep 3600
      done
      EOF'

networks:
  default:
    external:
      name: nginx-proxy
